CREATE ROLE developer WITH
    LOGIN
    SUPERUSER
    CREATEDB
    CREATEROLE
    NOREPLICATION
    NOBYPASSRLS
    PASSWORD 'developer';

CREATE ROLE tester WITH
    LOGIN
    SUPERUSER
    CREATEDB
    CREATEROLE
    NOREPLICATION
    NOBYPASSRLS
    PASSWORD 'tester';

CREATE DATABASE development WITH OWNER developer ENCODING 'UTF8' LC_COLLATE 'es_ES.utf8' LC_CTYPE 'es_ES.utf8' TEMPLATE template1 CONNECTION LIMIT -1 TABLESPACE pg_default IS_TEMPLATE false;
CREATE DATABASE testing WITH OWNER tester ENCODING 'UTF8' LC_COLLATE 'es_ES.utf8' LC_CTYPE 'es_ES.utf8' TEMPLATE template1 CONNECTION LIMIT -1 TABLESPACE pg_default IS_TEMPLATE false;

